export const iirsa = [
    {
      inicio: "",
      fim: "1947",
      eixo: "Capricornio",
      codigo: "CAP91",
      nome_projeto:
        "CORREDOR FERROVIARIO BIOCE�NICO, TRAMO CHILE (ANTOFAGASTA � SOCOMPA)",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 501000000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-24.042218,-69.349385",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1317",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2000",
      fim: "2002",
      eixo: "Escudo Guayanes",
      codigo: "GUY43",
      nome_projeto: "RUTA LINDEN - GEORGETOWN",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 0,
      pais: "GUYANA",
      fonte_investimento: "P�blico",
      geolocalizacao: "6.407649,-58.229563",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1415",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2002",
      fim: "2004",
      eixo: "Del Sur",
      codigo: "DES07",
      nome_projeto:
        "CONSTRUCCI�N DE INTERCONEXI�N A 500 KV TRAMO CHOELE CHOEL - PUERTO MADRYN",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 70000000,
      pais: "ARGENTINA",
      fonte_investimento: "CAF, Tesouro Nacional",
      geolocalizacao: "-41.13659,-65.403788",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=160",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2004",
      eixo: "Escudo Guayanes",
      codigo: "GUY10",
      nome_projeto: "PUENTE SOBRE EL R�O ARRAYA",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 1500000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "3.35595,-59.903522",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=184",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2001",
      fim: "2004",
      eixo: "Escudo Guayanes",
      codigo: "GUY42",
      nome_projeto: "RUTA BOA VISTA - BONFIM",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 15000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional Brasileiro",
      geolocalizacao: "3.076829,-60.259286",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1414",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2005",
      eixo: "Andino",
      codigo: "AND13",
      nome_projeto: "MEJORAMIENTO DEL PUENTE JOS� ANTONIO P�EZ",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 1280000,
      pais: "COLOMBIA",
      fonte_investimento: "Governo Colombiano",
      geolocalizacao: "7.088645, -70.740268",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=58",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2005",
      eixo: "Del Sur",
      codigo: "DES11",
      nome_projeto:
        "PAVIMENTACI�N DEL TRAMO HASTA LA FRONTERA CON ARGENTINA, ACCESO A PINO HACHADO RUTA CH-181",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 5000000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-38.450186,-71.626021",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=164",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2006",
      eixo: "Interoceanico Central",
      codigo: "IOC13",
      nome_projeto: "CONTORNO FERROVIARIO DE CAMPO GRANDE",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 31000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-20.537089,-54.516683",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=219",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2004",
      fim: "2006",
      eixo: "Amazonas",
      codigo: "AMA34",
      nome_projeto:
        "PROGRAMA DE MANEJO AMBIENTAL Y TERRITORIAL (RUTA CUIAB� - SANTAR�M) (BR-163 / MT / PA)",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 12000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-14.399778, -56.109298",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=35",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2006",
      eixo: "Peru-Brasil-Bolivia",
      codigo: "PBB03",
      nome_projeto: "PUENTE SOBRE EL R�O ACRE",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 12000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-10.941524,-69.577068",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=321",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2007",
      eixo: "Del Sur",
      codigo: "DES13",
      nome_projeto: "REPARACI�N DEL T�NEL LAS RA�CES",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 10500000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-38.55776,-71.498996",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=166",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2008",
      eixo: "Mercosur-Chile",
      codigo: "MCC14",
      nome_projeto:
        "CONSTRUCCI�N DEL TRAMO SANTA MAR�A - ROSARIO DO SUL (BR-158 / RS)",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 30000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-29.973484,-54.395835",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=264",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2008",
      eixo: "Peru-Brasil-Bolivia",
      codigo: "PBB59",
      nome_projeto: "L�NEA DE TRANSMISI�N SAN GAB�N - PUERTO MALDONADO",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 23617063,
      pais: "PERU",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-13.008596,-69.789137",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=940",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2008",
      eixo: "Mercosur-Chile",
      codigo: "MCC46",
      nome_projeto: "MEJORAS AL ACCESO VIAL PUERTO DE VALPARA�SO",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 105000000,
      pais: "CHILE",
      fonte_investimento: "P�blico",
      geolocalizacao: "-33.068248,-71.607067",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=296",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2007",
      fim: "2009",
      eixo: "Andino",
      codigo: "AND26",
      nome_projeto:
        "CARRETERA PUERTO INCA - HUAQUILLAS Y PUENTE INTERNACIONAL EN HUAQUILLAS - AGUAS VERDES, PASO LATERAL EN HUAQUILLAS",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 85817183,
      pais: "ECUADOR",
      fonte_investimento: "UE , Tesouro Nacional",
      geolocalizacao: "-3.534308, -80.375622",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=71",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2003",
      fim: "2009",
      eixo: "Amazonas",
      codigo: "AMA16",
      nome_projeto: "CARRETERA TARAPOTO - YURIMAGUAS",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 231712828,
      pais: "PERU",
      fonte_investimento: "Tesouro Nacional, BID, Privado",
      geolocalizacao: "-6.238647, -76.274123",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=17",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2009",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP36",
      nome_projeto: "ESTACI�N TRANSFORMADORA EN MERCEDES",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 25000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-29.181192,-58.094339",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=727",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2003",
      fim: "2009",
      eixo: "Capricornio",
      codigo: "CAP02",
      nome_projeto:
        "IMPLEMENTACI�N DEL CONTROL INTEGRADO DE �NICA CABECERA PASO DE JAMA",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 4000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-23.237282,-67.023042",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=121",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2009",
      eixo: "Interoceanico Central",
      codigo: "IOC20",
      nome_projeto:
        "MEJORAMIENTO DEL TRAMO FERROVIARIO CORUMB� - CAMPO GRANDE (FERROV�A DEL PANTANAL)",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 22000000,
      pais: "BRASIL",
      fonte_investimento: "Varios",
      geolocalizacao: "-19.753507,-56.160063",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=226",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2004",
      fim: "2009",
      eixo: "Andino",
      codigo: "AND38",
      nome_projeto:
        "MEJORAMIENTO Y REHABILITACI�N DEL TRAMO NARUPA - GUAMANIYACU",
      grupo: "G06",
      etapa: "CONCLUIDO",
      investimento_total: 23540825,
      pais: "ECUADOR",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-0.780927,-77.78343",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=83",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2009",
      eixo: "Interoceanico Central",
      codigo: "IOC33",
      nome_projeto: "PASO DE FRONTERA PISIGA - COLCHANE",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 10000000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-19.27599,-68.621823",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=239",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2002",
      fim: "2009",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP11",
      nome_projeto:
        "PAVIMENTACI�N DEL TRAMO CARRETERO SANTA ROSA - PUERTO ANTEQUERA (RUTA NACIONAL N� 11)",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 47000000,
      pais: "PARAGUAY",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-23.951673,-56.860583",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=670",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2007",
      fim: "2009",
      eixo: "Andino",
      codigo: "AND57",
      nome_projeto:
        "PROYECTO INTERCONEXI�N EL�CTRICA COLOMBIA - ECUADOR. L�NEA 230 KV ENTRE SUBESTACIONES PASTO (COLOMBIA) Y QUITO (ECUADOR)",
      grupo: "G09",
      etapa: "CONCLUIDO",
      investimento_total: 45400000,
      pais: "ECUADOR",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "0.49821,-77.895868",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=107",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2007",
      fim: "2009",
      eixo: "Escudo Guayanes",
      codigo: "GUY11",
      nome_projeto: "PUENTE SOBRE EL R�O TAKUTU",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 10000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "3.380626,-59.811364",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=185",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2008",
      fim: "2010",
      eixo: "Andino",
      codigo: "AND89",
      nome_projeto: "CARRETERA SULLANA - MACARA - LOJA",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 48381207,
      pais: "PERU",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-4.665341,-80.330499",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1343",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2007",
      fim: "2010",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP34",
      nome_projeto: "CENTRAL TERMOEL�CTRICA BELGRANO EN CAMPANA",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 668000000,
      pais: "ARGENTINA",
      fonte_investimento: "Varios",
      geolocalizacao: "-34.185027,-59.00746",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=725",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2007",
      fim: "2010",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP35",
      nome_projeto: "CENTRAL TERMOEL�CTRICA SAN MART�N EN TIMB�ES",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 738000000,
      pais: "ARGENTINA",
      fonte_investimento: "Varios",
      geolocalizacao: "-32.579544,-60.792436",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=726",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2001",
      fim: "2010",
      eixo: "Interoceanico Central",
      codigo: "IOC15",
      nome_projeto: "CIRCUNVALACI�N VIAL DE CORUMB�",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 8000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-19.046143,-57.660493",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=221",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2007",
      fim: "2010",
      eixo: "Mercosur-Chile",
      codigo: "MCC12",
      nome_projeto: "CONSTRUCCI�N DEL ANILLO VIAL SAN PABLO (TRAMO SUR)",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 2700000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional,Tesouro Municipal",
      geolocalizacao: "-23.695009,-46.665802",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=262",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2007",
      fim: "2010",
      eixo: "Mercosur-Chile",
      codigo: "MCC13",
      nome_projeto:
        "CONSTRUCCI�N Y PAVIMENTACI�N DE LA RUTA BR-282 / SC FLORIAN�POLIS - FRONTERA CON ARGENTINA",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 100000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-27.218269,-51.17583",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=263",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2008",
      fim: "2010",
      eixo: "Andino",
      codigo: "AND25",
      nome_projeto: "NUEVO AEROPUERTO REGIONAL DE SANTA ROSA",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 47127637,
      pais: "ECUADOR",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-3.443822, -79.997734",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=70",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2006",
      fim: "2010",
      eixo: "Peru-Brasil-Bolivia",
      codigo: "PBB01",
      nome_projeto:
        "PAVIMENTACI�N I�APARI - PUERTO MALDONADO - INAMBARI, INAMBARI - JULIACA / INAMBARI - CUSCO",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 1975976972,
      pais: "PERU",
      fonte_investimento: "Privado",
      geolocalizacao: "-18.175266,-63.683288",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=319",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2009",
      fim: "2010",
      eixo: "Amazonas",
      codigo: "AMA22",
      nome_projeto: "PUERTO DE BAY�VAR",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 70000000,
      pais: "PERU",
      fonte_investimento: "Privado",
      geolocalizacao: "-5.799706, -81.052204",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=23",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2010",
      eixo: "Interoceanico Central",
      codigo: "IOC39",
      nome_projeto: "REHABILITACI�N DEL PUENTE DE LA AMISTAD (PUENTE EISENHOWER)",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 3000000,
      pais: "BOLIVIA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-17.324329,-63.327317",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=245",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2005",
      fim: "2011",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP73",
      nome_projeto: "ACCESOS VIALES A ENCARNACI�N",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 26000000,
      pais: "PARAGUAY",
      fonte_investimento: "Binacional",
      geolocalizacao: "-27.341328,-55.854313",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=763",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2001",
      fim: "2011",
      eixo: "Amazonas",
      codigo: "AMA25",
      nome_projeto: "CARRETERA PAITA - TARAPOTO",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 273650767,
      pais: "PERU",
      fonte_investimento: "Tesouro Nacional, BID, Privado",
      geolocalizacao: "-5.818334, -78.304923",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=26",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2009",
      fim: "2011",
      eixo: "Andino",
      codigo: "AND88",
      nome_projeto: "CARRETERA SULLANA - EL ALAMOR",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 29517944,
      pais: "PERU",
      fonte_investimento: "BID, Tesouro Nacional",
      geolocalizacao: "-4.679382,-80.549001",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1342",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2006",
      fim: "2011",
      eixo: "Mercosur-Chile",
      codigo: "MCC101",
      nome_projeto: "CENTRAL NUCLEAR DE ATUCHA 2",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 740000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-33.967946,-59.206604",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=983",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2007",
      fim: "2011",
      eixo: "Andino",
      codigo: "AND21",
      nome_projeto:
        "CENTRO BINACIONAL DE ATENCI�N DE FRONTERA (CEBAF) EJE VIAL N�1",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 15871670,
      pais: "PERU",
      fonte_investimento: "UE, Tesouro Nacional",
      geolocalizacao: "-3.481359, -80.243050",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=66",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2011",
      eixo: "Capricornio",
      codigo: "CAP80",
      nome_projeto: "COMPLEJO PORTUARIO MEJILLONES",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 80000000,
      pais: "CHILE",
      fonte_investimento: "Privado",
      geolocalizacao: "-23.089088,-70.414769",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1288",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2011",
      eixo: "Escudo Guayanes",
      codigo: "GUY08",
      nome_projeto:
        "L�NEAS DE FIBRA �PTICA U OTRA TECNOLOG�A APROPIADA QUE INTERCONECTE CARACAS AL NORTE DE BRASIL",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 0,
      pais: "VENEZUELA",
      fonte_investimento: "-",
      geolocalizacao: "6.669527,-63.794678",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=182",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2009",
      fim: "2011",
      eixo: "Escudo Guayanes",
      codigo: "GUY35",
      nome_projeto: "PUENTE INTERNACIONAL SOBRE EL R�O OYAPOCK",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 60000000,
      pais: "BRASIL",
      fonte_investimento: "Binacional",
      geolocalizacao: "3.85617,-51.825714",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1160",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2011",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP107",
      nome_projeto: "PUERTO DE ENCARNACI�N",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 11800000,
      pais: "PARAGUAY",
      fonte_investimento: "Binacional",
      geolocalizacao: "-27.299988,-55.923973",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1226",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2006",
      fim: "2011",
      eixo: "Mercosur-Chile",
      codigo: "MCC64",
      nome_projeto: "REPRESA HIDROEL�CTRICA DE YACYRET�. LLENADO A COTA 83",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 1200000000,
      pais: "PARAGUAY",
      fonte_investimento: "Binacional",
      geolocalizacao: "-27.483644,-56.738924",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=314",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2012",
      eixo: "Mercosur-Chile",
      codigo: "MCC86",
      nome_projeto:
        "EXPANSI�N DEL PUERTO DE COLONIA (MUELLES, DRAGADO E INCORPORACI�N DE �REAS)",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 14000000,
      pais: "URUGUAY",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-34.474675,-57.84363",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=968",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2008",
      fim: "2012",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP94",
      nome_projeto:
        "MEJORA DE ACCESOS E INFRAESTRUCTURA PORTUARIA DEL PUERTO DE NUEVA PALMIRA",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 10000000,
      pais: "URUGUAY",
      fonte_investimento: "P�blico",
      geolocalizacao: "-33.880724,-58.419472",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=794",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2004",
      fim: "2012",
      eixo: "Amazonas",
      codigo: "AMA46",
      nome_projeto:
        "MEJORAMIENTO DE LA V�A GUAYAQUIL - EL TRIUNFO - LA TRONCAL - ZHUD - EL TAMBO - CA�AR - AZOGUES - PAUTE - AMALUZA - M�NDEZ Y MEJORAMIENTO Y AMPLIACI�N DEL TRAMO M�NDEZ - PUERTO MORONA",
      grupo: "G07",
      etapa: "CONCLUIDO",
      investimento_total: 140000000,
      pais: "ECUADOR",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-2.954578, -78.234510",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=641",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2009",
      fim: "2012",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP10",
      nome_projeto:
        "PAVIMENTACI�N DEL TRAMO CARRETERO SAN ESTANISLAO - PUERTO ROSARIO (RUTAS B11 Y B09)",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 66500000,
      pais: "PARAGUAY",
      fonte_investimento: "BID, Tesouro Nacional",
      geolocalizacao: "-24.552572,-56.801547",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=669",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2010",
      fim: "2012",
      eixo: "Interoceanico Central",
      codigo: "IOC30",
      nome_projeto:
        "PAVIMENTACI�N PORTO LIM�O - FRONTERA CON BOLIVIA (SAN MAT�AS)",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 13000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-16.205168,-58.039151",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=236",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2011",
      fim: "2012",
      eixo: "Mercosur-Chile",
      codigo: "MCC115",
      nome_projeto:
        "REACONDICIONAMIENTO DE LA FERROV�A RIVERA - SANTANA DO LIVRAMENTO - CACEQUI",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 5000000,
      pais: "BRASIL",
      fonte_investimento: "Privado",
      geolocalizacao: "-30.362376,-55.172269",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1222",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2012",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP95",
      nome_projeto:
        "REACTIVACI�N DEL PUERTO DE PAYSAND�, ACCESOS Y �REA DE ALMACENAJE",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 6000000,
      pais: "URUGUAY",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-32.316293,-58.103773",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=795",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2012",
      eixo: "Interoceanico Central",
      codigo: "IOC66",
      nome_projeto:
        "REHABILITACI�N Y CONCESI�N DEL FERROCARRIL ARICA - LA PAZ (TRAMO CHILENO)",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 60000000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-18.021681,-69.818841",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1220",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2008",
      fim: "2012",
      eixo: "Peru-Brasil-Bolivia",
      codigo: "PBB63",
      nome_projeto:
        "TRAMO 1 DE LA CARRETERA INTEROCE�NICA IIRSA SUR: SAN JUAN DE MARCONA - ABANCAY - CUSCO - URCOS",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 145418497,
      pais: "PERU",
      fonte_investimento: "Privado",
      geolocalizacao: "-14.400573,-73.380945",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1345",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2013",
      eixo: "Mercosur-Chile",
      codigo: "MCC84",
      nome_projeto: "AEROPUERTO DE ENCARNACI�N",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 12000000,
      pais: "PARAGUAY",
      fonte_investimento: "Binacional",
      geolocalizacao: "-27.221562,-55.834568",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=966",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2013",
      eixo: "Mercosur-Chile",
      codigo: "MCC139",
      nome_projeto: "CABLE �PTICO ENTRE BRASIL Y URUGUAY",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 0,
      pais: "BRASIL",
      fonte_investimento: "P�blico",
      geolocalizacao: "-30.901918,-55.550071",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1358",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2005",
      fim: "2013",
      eixo: "Andino",
      codigo: "AND31",
      nome_projeto:
        "CENTRO BINACIONAL DE ATENCI�N DE FRONTERA (CEBAF) SAN MIGUEL",
      grupo: "G06",
      etapa: "CONCLUIDO",
      investimento_total: 0,
      pais: "ECUADOR",
      fonte_investimento: "BID",
      geolocalizacao: "-3.497211, -80.218076",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=76",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2008",
      fim: "2013",
      eixo: "Amazonas",
      codigo: "AMA11",
      nome_projeto: "CONSTRUCCI�N DEL NUEVO AEROPUERTO DE TENA",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 54599943,
      pais: "ECUADOR",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-0.986865, -77.818490",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=12",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2011",
      fim: "2013",
      eixo: "Andino",
      codigo: "AND91",
      nome_projeto:
        "CONSTRUCCI�N DEL NUEVO PUENTE INTERNACIONAL DE RUMICHACA Y MEJORAMIENTO DEL PUENTE EXISTENTE",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 4100000,
      pais: "COLOMBIA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "0.81405,-77.663898",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1409",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2011",
      fim: "2013",
      eixo: "Capricornio",
      codigo: "CAP67",
      nome_projeto: "L�NEA DE TRANSMISI�N 500 KV (ITAIP� - VILLA HAYES)",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 555000000,
      pais: "PARAGUAY",
      fonte_investimento: "Tesouro Nacional, FOCEM",
      geolocalizacao: "-25.254242,-56.072594",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=860",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2008",
      fim: "2013",
      eixo: "Amazonas",
      codigo: "AMA87",
      nome_projeto: "L�NEA DE TRANSMISI�N DE 500 KV DE TUCURU� A MANAOS",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 1320000000,
      pais: "BRASIL",
      fonte_investimento: "Varios",
      geolocalizacao: "-3.754821, -49.643531",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=1390",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2013",
      eixo: "Mercosur-Chile",
      codigo: "MCC66",
      nome_projeto: "L�NEA DE TRANSMISI�N ITAIP� - LONDRINA - ARARAQUARA",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 149144214,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-23.450268,-50.92932",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=316",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2013",
      eixo: "Mercosur-Chile",
      codigo: "MCC47",
      nome_projeto:
        "PAVIMENTACI�N DEL TRAMO PUENTE ARMERILLO - PASO PEHUENCHE (RUTA CH-115)",
      grupo: "G06",
      etapa: "CONCLUIDO",
      investimento_total: 60000000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-35.866013,-70.759183",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=297",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2002",
      fim: "2014",
      eixo: "Mercosur-Chile",
      codigo: "MCC19",
      nome_projeto:
        "ADECUACI�N DEL CORREDOR R�O BRANCO - MONTEVIDEO - COLONIA - NUEVA PALMIRA: RUTAS N� 1, 11, 8, 17, 18 Y 26, RUTAS 23 Y 12",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 276185000,
      pais: "URUGUAY",
      fonte_investimento:
        "BID, CAF, Banco Muncial, Tesouro Nacional, FOCEM, Privado",
      geolocalizacao: "-33.633672,-55.938072",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=269",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2008",
      fim: "2014",
      eixo: "Interoceanico Central",
      codigo: "IOC69",
      nome_projeto: "AMPLIACI�N DEL AEROPUERTO DE IQUIQUE",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 16600000,
      pais: "CHILE",
      fonte_investimento: "Privado",
      geolocalizacao: "-20.546694,-70.179486",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1247",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2010",
      fim: "2014",
      eixo: "Capricornio",
      codigo: "CAP46",
      nome_projeto: "CONCESI�N AUTOPISTA ANTOFAGASTA",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 370000000,
      pais: "CHILE",
      fonte_investimento: "Privado",
      geolocalizacao: "-23.425492,-70.038899",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=871",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2007",
      fim: "2014",
      eixo: "Amazonas",
      codigo: "AMA55",
      nome_projeto: "CONEXI�N VIAL RIO BRANCO - CRUZEIRO DO SUL (BR-364 / AC)",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 573000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-8.551902, -69.932452",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=920",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2014",
      eixo: "Mercosur-Chile",
      codigo: "MCC02",
      nome_projeto:
        "CONSTRUCCI�N E IMPLANTACI�N DE CONTROL INTEGRADO DE CARGA EN PASO DE LOS LIBRES",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 10000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-29.72914,-57.107648",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=252",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2014",
      eixo: "Amazonas",
      codigo: "AMA105",
      nome_projeto: "FERROV�A NORTE - SUR FASE III (PALMAS - CAMPINORTE)",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 600000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-10.069890, -48.594078",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=1408",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2008",
      fim: "2014",
      eixo: "Capricornio",
      codigo: "CAP03",
      nome_projeto:
        "INTERCONEXI�N EL�CTRICA NOA (NOROESTE ARGENTINO) - NEA (NORESTE ARGENTINO)",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 725000000,
      pais: "ARGENTINA",
      fonte_investimento: "BID, Tesouro Nacional",
      geolocalizacao: "-26.088552,-62.083029",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=122",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2011",
      fim: "2014",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP116",
      nome_projeto: "L�NEA DE ALTA TENSI�N MERCEDES - GOYA",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 25000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-29.161117,-58.681104",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1297",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2014",
      eixo: "Peru-Brasil-Bolivia",
      codigo: "PBB18",
      nome_projeto:
        "L�NEA DE TRANSMISI�N ENTRE LAS DOS CENTRALES HIDROEL�CTRICAS DEL R�O MADEIRA Y EL SISTEMA CENTRAL",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 3823000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional, Privado",
      geolocalizacao: "-9.037943,-64.265812",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=336",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2012",
      fim: "2014",
      eixo: "Interoceanico Central",
      codigo: "IOC67",
      nome_projeto: "MEJORAMIENTO DEL AEROPUERTO DE TACNA",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 51509000,
      pais: "PERU",
      fonte_investimento: "Privado",
      geolocalizacao: "-18.050454,-70.276388",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=100",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2010",
      fim: "2014",
      eixo: "Interoceanico Central",
      codigo: "IOC62",
      nome_projeto: "MEJORAMIENTO DEL PUERTO DE MATARANI",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 37000000,
      pais: "PERU",
      fonte_investimento: "Privado",
      geolocalizacao: "-17.001304,-72.107886",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=961",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2010",
      fim: "2014",
      eixo: "Interoceanico Central",
      codigo: "IOC74",
      nome_projeto: "MEJORAMIENTO DEL TRAMO CONCEPCI�N - PEDRO JUAN CABALLERO",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 12500000,
      pais: "PARAGUAY",
      fonte_investimento: "Banco Mundial",
      geolocalizacao: "-23.012837,-56.574848",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1252",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2014",
      eixo: "Andino",
      codigo: "AND35",
      nome_projeto:
        "MEJORAMIENTO Y REHABILITACI�N DEL TRAMO BELLA UNI�N - GUALAQUIZA",
      grupo: "G06",
      etapa: "CONCLUIDO",
      investimento_total: 23202179,
      pais: "ECUADOR",
      fonte_investimento: "CAF",
      geolocalizacao: "-3.088272,-78.450858",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=80",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2007",
      fim: "2014",
      eixo: "Andino",
      codigo: "AND61",
      nome_projeto: "PROYECTOS DE INTERCONEXI�N GAS�FERA",
      grupo: "G09",
      etapa: "CONCLUIDO",
      investimento_total: 335000000,
      pais: "COLOMBIA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "10.957011,-72.232592",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=111",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2012",
      fim: "2014",
      eixo: "Amazonas",
      codigo: "AMA24",
      nome_projeto: "PUERTO DE PAITA",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 176662000,
      pais: "PERU",
      fonte_investimento: "Privado",
      geolocalizacao: "-5.082806, -81.105334",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=25",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2014",
      eixo: "Amazonas",
      codigo: "AMA09",
      nome_projeto:
        "REHABILITACI�N Y PAVIMENTACI�N DEL TRAMO SAN LORENZO - EL CARMEN",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 75970269,
      pais: "ECUADOR",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "0.068224, -76.774030",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=10",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2012",
      fim: "2014",
      eixo: "Amazonas",
      codigo: "AMA67",
      nome_projeto: "TERMINAL DE EMBARQUE DE MINERALES DEL CALLAO",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 113205000,
      pais: "PERU",
      fonte_investimento: "Privado",
      geolocalizacao: "-12.039827, -77.148244",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=1333",
      info_fonte: "IIRSA"
    },
    {
      inicio: "1994",
      fim: "2014",
      eixo: "Andino",
      codigo: "AND18",
      nome_projeto:
        "TRAMOS FALTANTES DE PAVIMENTACI�N ENTRE VILLAVICENCIO Y PUERTO L�PEZ",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 26000000,
      pais: "COLOMBIA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "4.089520, -73.576834",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=63",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2009",
      fim: "2015",
      eixo: "Amazonas",
      codigo: "AMA03",
      nome_projeto:
        "ACCESO Y ADECUACI�N DEL PUERTO DE PUERTO AS�S (MUELLE LA ESMERALDA)",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 3000000,
      pais: "COLOMBIA",
      fonte_investimento: "Governo Colombiano",
      geolocalizacao: "0.471001, -76.475173",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=4",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2013",
      fim: "2015",
      eixo: "Interoceanico Central",
      codigo: "IOC25",
      nome_projeto: "�REA DE CONTROL INTEGRADO PUERTO SU�REZ - CORUMB�",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 2000000,
      pais: "BOLIVIA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-19.027902,-57.707612",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=231",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2015",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP127",
      nome_projeto: "CONSTRUCCI�N DE PUERTO BUSCH",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 0,
      pais: "BOLIVIA",
      fonte_investimento: "P�blico",
      geolocalizacao: "-18.986192,-57.735084",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1477",
      info_fonte: "IIRSA"
    },
    {
      inicio: "1994",
      fim: "2015",
      eixo: "Andino",
      codigo: "AND01",
      nome_projeto: "CORREDOR VIAL SANTA MARTA - PARAGUACH�N",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 411158974,
      pais: "COLOMBIA",
      fonte_investimento: "Varios",
      geolocalizacao: "11.360741, -72.132176",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=46",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2012",
      fim: "2015",
      eixo: "Andino",
      codigo: "AND14",
      nome_projeto: "CULMINACI�N DE LA PAVIMENTACI�N TAME - ARAUCA",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 10548000,
      pais: "COLOMBIA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "6.880366, -71.664180",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=59",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2015",
      fim: "2015",
      eixo: "Andino",
      codigo: "AND12",
      nome_projeto: "CULMINACI�N DE LA PAVIMENTACI�N TAME - VILLAVICENCIO",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 3634264,
      pais: "COLOMBIA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "4.521681, -73.073343",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=57",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2015",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP117",
      nome_projeto: "L�NEA DE ALTA TENSI�N MERCEDES - PASO DE LOS LIBRES",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 15000000,
      pais: "ARGENTINA",
      fonte_investimento: "FOCEM",
      geolocalizacao: "-29.444508,-57.588326",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1298",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2011",
      fim: "2015",
      eixo: "Amazonas",
      codigo: "AMA70",
      nome_projeto: "MUELLE DE LETICIA",
      grupo: "G06",
      etapa: "CONCLUIDO",
      investimento_total: 3340981,
      pais: "COLOMBIA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-4.223520, -69.945565",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=1336",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2012",
      fim: "2015",
      eixo: "Amazonas",
      codigo: "AMA71",
      nome_projeto: "PUERTO DE PROVIDENCIA - PRIMERA ETAPA",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 25000000,
      pais: "ECUADOR",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-0.460438, -76.492510",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=1357",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2013",
      fim: "2016",
      eixo: "Capricornio",
      codigo: "CAP89",
      nome_projeto: "COMPLEJO FRONTERIZO HITO CAJ�N",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 1160000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-22.880998,-67.798724",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1315",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2016",
      eixo: "Interoceanico Central",
      codigo: "IOC85",
      nome_projeto: "CONSTRUCCI�N COMPLEJO FRONTERIZO CHUNGAR�",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 37000000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-18.285236,-69.076118",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1355",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2014",
      fim: "2016",
      eixo: "Amazonas",
      codigo: "AMA102",
      nome_projeto: "CONSTRUCCI�N DEL NUEVO PUERTO DE YURIMAGUAS",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 50320000,
      pais: "PERU",
      fonte_investimento: "Privado",
      geolocalizacao: "-5.851191, -76.161293",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=1405",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2016",
      eixo: "Mercosur-Chile",
      codigo: "MCC163",
      nome_projeto: "DOBLE CALZADA RUTA 5 LA SERENA-VALLENAR",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 388000000,
      pais: "CHILE",
      fonte_investimento: "Privado",
      geolocalizacao: "-29.247049,-71.042026",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1452",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2014",
      fim: "2016",
      eixo: "Andino",
      codigo: "AND56",
      nome_projeto:
        "FORTALECIMIENTO DE LAS INTERCONEXIONES CUATRICENTENARIO - CUESTECITAS Y EL COROZO - SAN MATEO",
      grupo: "G09",
      etapa: "CONCLUIDO",
      investimento_total: 125200000,
      pais: "VENEZUELA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "9.435138,-72.12594",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=106",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2014",
      fim: "2016",
      eixo: "Andino",
      codigo: "AND08",
      nome_projeto: "REHABILITACI�N RUMICHACA - PASTO - CHACHAG��",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 164030839,
      pais: "COLOMBIA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "0.863694, -77.580965",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=53",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2014",
      fim: "2016",
      eixo: "Interoceanico Central",
      codigo: "IOC89",
      nome_projeto:
        "SISTEMA DE RECEPCI�N, ALMACENAMIENTO Y EMBARQUE DE CONCENTRADOS DE MINERALES EN EL PUERTO DE MATARANI",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 230000000,
      pais: "PERU",
      fonte_investimento: "Privado",
      geolocalizacao: "-16.999074,-72.105234",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1444",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2012",
      fim: "2016",
      eixo: "Amazonas",
      codigo: "AMA66",
      nome_projeto: "TERMINAL NORTE MULTIPROP�SITO DEL CALLAO",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 390200000,
      pais: "PERU",
      fonte_investimento: "Privado",
      geolocalizacao: "-12.047193, -77.145470",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=1332",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Interoceanico Central",
      codigo: "",
      nome_projeto: "CARRETERA TOLEDO - PISIGA",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 130500000,
      pais: "BOLIVIA",
      fonte_investimento: "CAF, Tesouro Nacional",
      geolocalizacao: "-18.729922,-68.01217",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=238",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Interoceanico Central",
      codigo: "",
      nome_projeto:
        "CONSTRUCCI�N DE LA CARRETERA PAIL�N - SAN JOS� - PUERTO SU�REZ",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 409000000,
      pais: "BOLIVIA",
      fonte_investimento: "BID, CAF, UE, Bancos Privados",
      geolocalizacao: "-18.293482,-60.269354",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=228",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Mercosur-Chile",
      codigo: "",
      nome_projeto: "CONSTRUCCI�N DE PUERTO SECO PR�XIMO AL PUERTO DE MONTEVIDEO",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 25000000,
      pais: "URUGUAY",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-34.877649,-56.204116",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=972",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Andino",
      codigo: "",
      nome_projeto: "CULMINACI�N DE PAVIMENTACI�N POTOS� - TARIJA",
      grupo: "G08",
      etapa: "CONCLUIDO",
      investimento_total: 238200000,
      pais: "BOLIVIA",
      fonte_investimento: "CAF, Tesouro Nacional, BID, BNDES",
      geolocalizacao: "-20.577146,-65.213189",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=93",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "",
      nome_projeto: "DISE�O Y CONSTRUCCI�N DEL CANAL ALTERNATIVO CASA BLANCA",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 7400000,
      pais: "URUGUAY",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-32.387379,-58.173244",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=792",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2015",
      fim: "2017",
      eixo: "Capricornio",
      codigo: "",
      nome_projeto: "ESTUDIO DE OPTIMIZACI�N DEL NODO �EEMBUC� - R�O BERMEJO",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 503477,
      pais: "PARAGUAY",
      fonte_investimento: "FONPLATA",
      geolocalizacao: "-26.861576,-58.313464",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=142",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Interoceanico Central",
      codigo: "",
      nome_projeto:
        "INSTALACI�N DE FIBRA �PTICA A LO LARGO DE LA CARRETERA PAIL�N - PUERTO SU�REZ",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 11987651,
      pais: "BOLIVIA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-18.293482,-60.269354",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=230",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "",
      nome_projeto:
        "MEJORA EN LOS ACCESOS FLUVIALES A PUERTOS URUGUAYOS EN EL R�O URUGUAY",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 1000000,
      pais: "URUGUAY",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-33.094009,-58.268523",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=783",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2013",
      fim: "2017",
      eixo: "Amazonas",
      codigo: "AMA39",
      nome_projeto: "MEJORAMIENTO DE LA NAVEGABILIDAD DEL R�O MORONA",
      grupo: "G06",
      etapa: "CONCLUIDO",
      investimento_total: 5241000,
      pais: "PERU",
      fonte_investimento: "BID",
      geolocalizacao: "-3.707431, -77.561448",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=40",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Mercosur-Chile",
      codigo: "MCC51",
      nome_projeto: "MEJORAS EN EL PUERTO DE SAN ANTONIO",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 370000000,
      pais: "CHILE",
      fonte_investimento: "Privado",
      geolocalizacao: "",
      info_extra: "",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Interoceanico Central",
      codigo: "",
      nome_projeto: "PASO DE FRONTERA INFANTE RIVAROLA - CA�ADA ORURO",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 1900000,
      pais: "PARAGUAY",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-21.672698,-62.458028",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=215",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2015",
      fim: "2017",
      eixo: "Capricornio",
      codigo: "",
      nome_projeto:
        "PAVIMENTACI�N DE LA RUTA NACIONAL N� 51: CAMPO QUIJANO - PASO DE SICO",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 24305347,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-24.375917,-66.448437",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1242",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2015",
      fim: "2017",
      eixo: "Capricornio",
      codigo: "",
      nome_projeto:
        "PAVIMENTACI�N DE LA RUTA NACIONAL N� 89: EMPALME RUTA NACIONAL N� 16 CHACO - EMPALME RUTA NACIONAL N� 34 TABOADA",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 24305347,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-27.358262,-62.244911",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=908",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2015",
      fim: "2017",
      eixo: "Capricornio",
      codigo: "",
      nome_projeto:
        "PAVIMENTACI�N DE LA RUTA NACIONAL N� 95: EMPALME RUTA NACIONAL N� 81 - VILLA �NGELA",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 90000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-26.428143,-60.248914",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=869",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "",
      nome_projeto:
        "PAVIMENTACI�N DE LA RUTA PROVINCIAL N� 9: COLONIA CANO - EL COLORADO",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 60000000,
      pais: "ARGENTINA",
      fonte_investimento: "BID",
      geolocalizacao: "-26.569435,-58.840116",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=752",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Capricornio",
      codigo: "CAP92",
      nome_projeto: "PAVIMENTACI�N POTOS� - TUPIZA - VILLAZ�N",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 180400000,
      pais: "BOLIVIA",
      fonte_investimento: "CAF, BNDES",
      geolocalizacao: "-18.175266,-63.683288",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=210",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2013",
      fim: "2017",
      eixo: "Mercosur-Chile",
      codigo: "MCC18",
      nome_projeto: "RECUPERACI�N DE PORTO ALEGRE - URUGUAIANA (BR-290 / RS)",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 250000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-30.075013,-54.194274",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=268",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Amazonas",
      codigo: "AMA84",
      nome_projeto:
        "REHABILITACI�N DE LA CARRETERA BR-222 A�AIL�NDIA (MA) - PORTO DE ITAQUI (MA)",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 180000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-4.552448, -46.893283",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=1387",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Amazonas",
      codigo: "AMA85",
      nome_projeto:
        "REHABILITACI�N DE LA CARRETERA BR-230 BALSAS (MA) - MARAB� (PA)",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 0,
      pais: "BRASIL",
      fonte_investimento: "-",
      geolocalizacao: "-5.371880, -49.038231",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=1388",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2017",
      eixo: "Mercosur-Chile",
      codigo: "MCC45",
      nome_projeto: "RUTA INTERNACIONAL CH-60 (SECTOR VALPARA�SO - LOS ANDES)",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 447000000,
      pais: "CHILE",
      fonte_investimento: "Privado/Corporativo",
      geolocalizacao: "-32.923231,-71.124462",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=295",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2015",
      fim: "2018",
      eixo: "Capricornio",
      codigo: "CAP49",
      nome_projeto:
        "DUPLICACI�N Y REHABILITACI�N DE LA RUTA N� 50: TRAMO PICHANAL - OR�N",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 35000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-23.218084,-64.275236",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=874",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2018",
      eixo: "Mercosur-Chile",
      codigo: "",
      nome_projeto:
        "PAVIMENTACI�N DE LA RUTA NACIONAL N� 145: EMPALME RUTA NACIONAL N� 40 SUR - ACCESO AL PASO PEHUENCHE",
      grupo: "G06",
      etapa: "CONCLUIDO",
      investimento_total: 63000000,
      pais: "ARGENTINA",
      fonte_investimento: "CAF, Tesouro Nacional",
      geolocalizacao: "-35.889331,-70.101103",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=287",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2018",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP105",
      nome_projeto: "RECONSTRUCCI�N DE LA FERROV�A GARUP� - POSADAS",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 100000000,
      pais: "ARGENTINA",
      fonte_investimento: "CAF",
      geolocalizacao: "-27.434172,-55.854947",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=880",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "2018",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP67",
      nome_projeto: "RECUPERACI�N DEL RAMAL FERROVIARIO Z�RATE - ROSARIO",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 42000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-33.562738,-59.837939",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=782",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Capricornio",
      codigo: "",
      nome_projeto:
        "ACCESOS AL PASO DE JAMA (RUTA NACIONAL N� 52 - EMPALME RUTA NACIONAL N� 9 - L�MITE CON CHILE)",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 54000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-23.486097,-66.266428",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=120",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2011",
      fim: "",
      eixo: "Capricornio",
      codigo: "CAP88",
      nome_projeto: "AEROPUERTO DE ANTOFAGASTA",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 28000000,
      pais: "CHILE",
      fonte_investimento: "Privado",
      geolocalizacao: "-23.44883,-70.44217",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1314",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Capricornio",
      codigo: "",
      nome_projeto: "AMPLIACI�N DEL COMPLEJO PORTUARIO MEJILLONES (FASE I)",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 120000000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional, Privado",
      geolocalizacao: "-23.069792,-70.385556",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=127",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Mercosur-Chile",
      codigo: "",
      nome_projeto: "CENTRAL T�RMICA DE CICLO COMBINADO DE PUNTAS DEL TIGRE",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 170000000,
      pais: "URUGUAY",
      fonte_investimento: "P�blico",
      geolocalizacao: "-34.750762,-56.542784",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=276",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Capricornio",
      codigo: "",
      nome_projeto:
        "CENTRO DE CONTROL INTEGRADO BARRANCAS BLANCAS (PASO DE FRONTERA PIRCAS NEGRAS)",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 5000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-28.173832,-69.144634",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1125",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "",
      nome_projeto: "CIRCUNVALACI�N DE LA CIUDAD DE SANTA FE",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 200000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Provincial",
      geolocalizacao: "-31.54991,-60.742694",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=747",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Peru-Brasil-Bolivia",
      codigo: "",
      nome_projeto:
        "COMPLEJO HIDROEL�CTRICO DEL R�O MADEIRA (HIDROEL�CTRICA SANTO ANTONIO E HIDROEL�CTRICA JIRAU)",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 18209000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional, Bancos Privados",
      geolocalizacao: "-9.269734,-64.636122",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=334",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Mercosur-Chile",
      codigo: "MCC04",
      nome_projeto:
        "CONCLUSI�N DE LA DUPLICACI�N DEL TRAMO VIAL BELO HORIZONTE - SAN PABLO (BR-381 / SP / MG)",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 1300000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-21.748047,-45.400063",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=254",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Interoceanico Central",
      codigo: "",
      nome_projeto:
        "CONSTRUCCI�N DE DOBLE V�A CONCESIONADA: AEROPUERTO DIEGO ARACENA - IQUIQUE",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 173000000,
      pais: "CHILE",
      fonte_investimento: "privado",
      geolocalizacao: "-20.417076,-70.151172",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1249",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Del Sur",
      codigo: "",
      nome_projeto:
        "CONSTRUCCI�N DE INTERCONEXI�N A 500 KV REGI�N COMAHUE - CUYO",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 350000000,
      pais: "ARGENTINA",
      fonte_investimento: "CAF, Tesouro Nacional",
      geolocalizacao: "-36.022623,-68.50968",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=159",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Capricornio",
      codigo: "",
      nome_projeto:
        "CONSTRUCCI�N DE VARIANTE RUTA NACIONAL N� 12, PASO POR CIUDAD DE POSADAS (PROVINCIA DE MISIONES)",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 35000000,
      pais: "ARGENTINA",
      fonte_investimento: "Binacional",
      geolocalizacao: "-27.456595,-55.947614",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=881",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Del Sur",
      codigo: "",
      nome_projeto: "CONSTRUCCI�N DEL COMPLEJO FRONTERIZO HUA HUM",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 7600000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-40.087768,-71.69967",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1412",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "",
      nome_projeto: "DESV�O DEL ARROYO AGUAPEY",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 64000000,
      pais: "PARAGUAY",
      fonte_investimento: "Binacional",
      geolocalizacao: "-27.285336,-56.367951",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=767",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Mercosur-Chile",
      codigo: "",
      nome_projeto:
        "DUPLICACI�N DE LA RUTA NACIONAL N� 14 ENTRE PASO DE LOS LIBRES Y GUALEGUAYCH�",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 780000000,
      pais: "ARGENTINA",
      fonte_investimento: "BID, Tesouro Nacional",
      geolocalizacao: "-31.358997,-57.907617",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=251",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2012",
      fim: "",
      eixo: "Andino",
      codigo: "AND60",
      nome_projeto: "EXTENSI�N DEL OLEODUCTO NOR-PERUANO",
      grupo: "G09",
      etapa: "CONCLUIDO",
      investimento_total: 0,
      pais: "PERU",
      fonte_investimento: "P�blico",
      geolocalizacao: "-18.175266,-63.683288",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=110",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2007",
      fim: "",
      eixo: "Amazonas",
      codigo: "AMA78",
      nome_projeto: "FERROV�A NORTE-SUR FASE II (A�AIL�NDIA - PALMAS)",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 2500000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-4.913980, -47.398406",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=1381",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Mercosur-Chile",
      codigo: "",
      nome_projeto: "L�NEA DE TRANSMISI�N YACYRET� - BUENOS AIRES",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 600000000,
      pais: "ARGENTINA",
      fonte_investimento: "CAF e Tesouro Nacional",
      geolocalizacao: "-31.20024,-57.733811",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=253",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Interoceanico Central",
      codigo: "",
      nome_projeto: "MEJORAMIENTO COMPLEJO FRONTERIZO CHACALLUTA",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 1000000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-18.315018,-70.313268",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1356",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Amazonas",
      codigo: "AMA36",
      nome_projeto:
        "MEJORAMIENTO DE LA NAVEGABILIDAD DEL SISTEMA SOLIM�ES - AMAZONAS",
      grupo: "G06",
      etapa: "CONCLUIDO",
      investimento_total: 8000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "3.304236, -60.387615",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=37",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Amazonas",
      codigo: "AMA48",
      nome_projeto:
        "MEJORAMIENTO DE LA V�A PUERTO BOL�VAR - PASAJE - SANTA ISABEL - GIR�N - CUENCA - PAUTE - AMALUZA - M�NDEZ - PUERTO MORONA",
      grupo: "G07",
      etapa: "CONCLUIDO",
      investimento_total: 100000000,
      pais: "ECUADOR",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-3.019302, -78.583473",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=643",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2004",
      fim: "",
      eixo: "Amazonas",
      codigo: "AMA47",
      nome_projeto:
        "MEJORAMIENTO DE LA V�A PUERTO BOL�VAR - SANTA ROSA - BALSAS - CHAGUARPAMBA - LOJA - ZAMORA - YANTZAZA - EL PANGUI - GUALAQUIZA - GRAL. LE�NIDAS PLAZA - M�NDEZ",
      grupo: "G07",
      etapa: "CONCLUIDO",
      investimento_total: 167669793,
      pais: "ECUADOR",
      fonte_investimento: "Tesouro Nacional, CAF",
      geolocalizacao: "-3.487922, -78.543657",
      info_extra: "http://cosiplan.org/proyectos/detalle_proyecto.aspx?h=642",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Interoceanico Central",
      codigo: "",
      nome_projeto: "MEJORAMIENTO DEL AEROPUERTO DE ARICA",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 10000000,
      pais: "CHILE",
      fonte_investimento: "Privado",
      geolocalizacao: "-18.349646,-70.336532",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=240",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Capricornio",
      codigo: "",
      nome_projeto: "OBRAS DE ADECUACI�N DEL PUERTO DE ANTOFAGASTA",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 18000000,
      pais: "CHILE",
      fonte_investimento: "Privado",
      geolocalizacao: "-23.649928,-70.403764",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=128",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Interoceanico Central",
      codigo: "IOC29",
      nome_projeto: "PASO DE FRONTERA SAN MAT�AS - C�CERES (PORTO LIM�O)",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 2000000,
      pais: "BRASIL",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-16.389685,-58.336484",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=235",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP58",
      nome_projeto:
        "PAVIMENTACI�N DE LA RUTA NACIONAL N� 11, TRAMO EMPALME RUTA PROVINCIAL N� 13",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 100000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Provincial",
      geolocalizacao: "-27.32835,-58.994186",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=749",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP59",
      nome_projeto:
        "PAVIMENTACI�N DE LA RUTA NACIONAL N� 11: TRAMO SANTA FE - SAN JUSTO",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 91300000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-31.127665,-60.666953",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=750",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2015",
      fim: "",
      eixo: "Mercosur-Chile",
      codigo: "MCC94",
      nome_projeto:
        "PAVIMENTACI�N DE LA RUTA NACIONAL N� 150: TRAMO ISCHIGUALASTO - L�MITE CON CHILE (PASO AGUA NEGRA)",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 55597690,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-30.261757,-68.747631",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=976",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Mercosur-Chile",
      codigo: "",
      nome_projeto:
        "PAVIMENTACI�N DE LA RUTA NACIONAL N� 40: ACCESO AL AEROPUERTO DE MENDOZA - L�MITE SAN JUAN",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 210000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-32.281161,-68.553318",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1364",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Capricornio",
      codigo: "",
      nome_projeto:
        "PAVIMENTACI�N DE LA RUTA NACIONAL N� 95: VILLA �NGELA - EMPALME RUTA PROVINCIAL N� 286 SANTA FE",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 37000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-28.426899,-61.24528",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=904",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Capricornio",
      codigo: "CAP102",
      nome_projeto: "PAVIMENTACI�N PASO OLLAG�E-CALAMA",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 70000000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-21.827801,-68.564543",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1446",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Capricornio",
      codigo: "CAP90",
      nome_projeto:
        "PAVIMENTACI�N RUTA B-243, CONEXI�N CH27 SAN PEDRO - TOCOPILLA - ANTOFAGASTA",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 1500000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-22.900739,-67.804493",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=1316",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2008",
      fim: "",
      eixo: "Interoceanico Central",
      codigo: "IOC36",
      nome_projeto:
        "PAVIMENTACI�N Y MEJORAMIENTO DE LA CARRETERA IQUIQUE - COLCHANE",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 42000000,
      pais: "CHILE",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-19.777805,-69.381364",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=242",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Hidrovia Paraguay-Parana",
      codigo: "HPP29",
      nome_projeto:
        "PROYECTO BINACIONAL MEJORAMIENTO DE LA NAVEGABILIDAD EN EL LAGO ITAIP�",
      grupo: "G02",
      etapa: "CONCLUIDO",
      investimento_total: 0,
      pais: "BRASIL",
      fonte_investimento: "",
      geolocalizacao: "-25.388186,-54.556916",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=720",
      info_fonte: "IIRSA"
    },
    {
      inicio: "2004",
      fim: "",
      eixo: "Andino",
      codigo: "AND64",
      nome_projeto:
        "PROYECTO INTERCONEXI�N EL�CTRICA COLOMBIA - VENEZUELA, PUERTO NUEVO - PUERTO P�EZ - PUERTO CARRE�O",
      grupo: "G09",
      etapa: "CONCLUIDO",
      investimento_total: 5000000,
      pais: "COLOMBIA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "5.982134,-68.722613",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=114",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Mercosur-Chile",
      codigo: "MCC48",
      nome_projeto: "PUERTO TERRESTRE LOS SAUCES (LOS ANDES)",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 61000000,
      pais: "CHILE",
      fonte_investimento: "Privado",
      geolocalizacao: "-32.839764,-70.542369",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=298",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Mercosur-Chile",
      codigo: "MCC52",
      nome_projeto:
        "RECONSTRUCCI�N Y AMPLIACI�N DE LA RUTA NACIONAL N� 168: T�NEL SUBFLUVIAL ENTRE PARAN� Y SANTA FE",
      grupo: "G04",
      etapa: "CONCLUIDO",
      investimento_total: 40000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-31.703724,-60.50335",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=302",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Mercosur-Chile",
      codigo: "MCC41",
      nome_projeto:
        "RUTA NACIONAL N� 7: CONSTRUCCI�N DE VARIANTE FERROVIARIA LAGUNA LA PICASA",
      grupo: "G03",
      etapa: "CONCLUIDO",
      investimento_total: 30000000,
      pais: "ARGENTINA",
      fonte_investimento: "Tesouro Nacional",
      geolocalizacao: "-34.348011,-62.264655",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=291",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Capricornio",
      codigo: "CAP06",
      nome_projeto:
        "RUTA NACIONAL N� 81: PAVIMENTACI�N LAS LOMITAS - EMPALME RUTA NACIONAL N� 34",
      grupo: "G01",
      etapa: "CONCLUIDO",
      investimento_total: 100000000,
      pais: "ARGENTINA",
      fonte_investimento: "CAF",
      geolocalizacao: "-24.56721,-61.06937",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=125",
      info_fonte: "IIRSA"
    },
    {
      inicio: "",
      fim: "",
      eixo: "Mercosur-Chile",
      codigo: "MCC61",
      nome_projeto: "SISTEMA DE ITAIP� (EXISTENTE)",
      grupo: "G05",
      etapa: "CONCLUIDO",
      investimento_total: 16000000000,
      pais: "BRASIL",
      fonte_investimento: "Binacional",
      geolocalizacao: "-25.397882,-54.576482",
      info_extra: "http://iirsa.org/proyectos/detalle_proyecto.aspx?h=311",
      info_fonte: "IIRSA"
    }
  ];